baseURL = "https://wisocn.github.io/"
languageCode = "en-us"
title = "wisocn.io"
theme = "pickles"

[Author]
  name = "Some Person"
  email = "youremail@domain.com"
  facebook = "username"
  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "username"
  github = "username"
  twitter = "username"

[Params]
  subtitle = "Hugo Blog Template for GitLab Pages"
